name: "Run (Release) Build Script"
description: "Runs a provided build script in the same environment used for release builds"

inputs:
  script:
    description: "Script to run"
    required: true
  arch:
    description: "CMake architecture"
  cmake_gen:
    description: "CMake generator"
  msvc_ver:
    description: "MSVC version"
  macosx_target_ver:
    description: "macOS Deployment Target version"
  cpack_gen:
    description: "CPack generator"

runs:
  using: "composite"
  steps:
    - name: Build native
      if: runner.os != 'Linux'
      env:
        BUILD_ARCH: ${{ inputs.build_arch }}
        BUILD_GEN: ${{ inputs.cmake_gen }}
        MSVC_VER: ${{ inputs.msvc_ver }}
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos_target_ver }}
        CPACK_GEN: ${{ inputs.cpack_gen }}
      shell: bash
      run: ${{ inputs.script }}

    - name: Build containerized
      if: runner.os == 'Linux'
      uses: ./.github/actions/linux-release-builder
      with:
        script: ${{ inputs.script }}
